add more analysis to flow

diff --git a/.github/workflows/Build.yaml b/.github/workflows/Build.yaml
--- a/.github/workflows/Build.yaml
+++ b/.github/workflows/Build.yaml
@@ -58,22 +58,37 @@ jobs:
       - name: Check build-logic
         run: ./gradlew check -p build-logic
 
-      - name: Check ktlint
-        run: ./gradlew ktlintCheck
-
-      - name: Check spotless
+      - name: Check Spotless
+        id: spotless_check
+        continue-on-error: true
         run: ./gradlew spotlessCheck :build-logic:convention:spotlessCheck
 
-#      - name: Apply Spotless
-#        run: ./gradlew spotlessApply
-#
-#      - name: Commit Spotless changes
-#        uses: stefanzweifel/git-auto-commit-action@v5
-#        with:
-#            commit_message: 🤖 Apply Spotless formatting
-#            file_pattern: '**/*.kt **/*.kts **/*.java **/*.xml'
+      - name: Prevent updating Spotless if this is a fork
+        id: checkfork_spotless
+        continue-on-error: false
+        if: steps.spotless_check.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          echo "::error::Spotless failed, please update  with: ./gradlew spotlessApply" && exit 1
 
+      - name: Apply Spotless if check failed and it's a PR
+        id: spotless_apply
+        if: steps.spotless_check.outcome == 'failure' && github.event_name == 'pull_request'
+        run: |
+          ./gradlew spotlessApply :build-logic:convention:spotlessApply
 
+      - name: Push new Spotless Apply if available
+        uses: stefanzweifel/git-auto-commit-action@v6.0.1
+        if: steps.spotless_apply.outcome == 'success'
+        with:
+          file_pattern: '**/*.kt **/*.kts **/*.java **/*.xml'
+          disable_globbing: true
+          commit_message: "🤖 Apply Spotless formatting"
+
+      - uses: github/codeql-action/upload-sarif@v2
+        if: success() || failure()
+        with:
+          sarif_file: build/detekt-merged.sarif
+          category: detekt
 
       - name: Check Dependency Guard
         id: dependencyguard_verify
@@ -173,6 +188,12 @@ jobs:
 
       - name: Check lint
         run: ./gradlew lintFossReliantRelease
+
+      - uses: github/codeql-action/upload-sarif@v2
+        if: success() || failure()
+        with:
+          sarif_file: build/lint-merged.sarif
+          category: lint
 
       - name: Upload lint reports (HTML)
         if: always()
